#!/bin/bash
echo "Good Morning"
echo "Good Morning"
echo "Good Morning"
echo "Good Morning"
echo "Good Morning"
echo "Good Morning...madhu"
echo "Good Morning...madhu"
echo "Good Morning...Raja"
echo "Good Morning...Raja"
